name: Update k8s image
description: Updates a container tag inside a Kubernetes manifest
branding:
  color: blue
  icon: anchor

inputs:
  manifest-path:
    description: Location of the manifest that will be updated
    required: true
  new-image-tag:
    description: New image tag
    default: '${{github.sha}}'
    required: false
  container-name:
    description: Name of the container that references the image to replace
    required: true
  multi-doc-error:
    description: |
      How to handle errors in yml multi-doc files: (ignore|warn|fail)
      For 'ignore' and 'warn' the step will not fail if at least one document in the multi-doc could be updated.
    required: false
    default: warn
outputs:
  old-image-tag:
    description: 'Previous image tag. For multi-doc only the last image-tag'

runs:
  using: 'node12'
  main: 'dist/index.js'
